version: 2
jobs:
  test-xcode-9-3:
    macos:
      xcode: "9.3.0"
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - checkout
      # Setup Ruby dependencies
      - restore_cache:
          key: 5-gems-{{ checksum "./PRODUCTNAME/Gemfile.lock" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Restore Ruby Gems
          command: |
            bundle check --gemfile ./PRODUCTNAME/Gemfile || bundle install --gemfile ./PRODUCTNAME/Gemfile
            bundle check --gemfile Gemfile || bundle install --gemfile Gemfile
      # Setup Python dependencies
      - restore_cache:
          key: 5-python-requirements-{{ checksum "requirements.txt" }}
      - run:
          name: Restore Python Packages
          command: |
            [[ -d .venv ]] || virtualenv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: 5-python-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "/Users/distiller/project/.venv"
      # Restore Pods cache
      - restore_cache:
          key: 3-pods-{{ checksum "./PRODUCTNAME/app/Podfile.lock" }}
      - run:
          name: Code Coverage
          command: |
            cd PRODUCTNAME/app
            bundle exec fastlane test
            rm build/develop-PRODUCTNAME-debug-PRODUCTNAME.log
      # Store xcov Code Coverage HTML report artifact 
      - store_artifacts:
          path: /Users/distiller/project/PRODUCTNAME/app/build/
          destination: code-coverage
      - run:
          name: Danger
          command: |
            bundle exec danger
      # Download CocoaPods specs via HTTPS (faster than Git)
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod repo update
      # Run tests
      - run:
          name: Test Pre-generated Cookiecutter Template
          command: |
            source .venv/bin/activate
            echo Testing branch ${CIRCLE_BRANCH}
            cookiecutter --no-input ./
            cd ProjectName/app
            bundle install
            bundle exec fastlane test
      - run:
          name: Test Template Generation from PRODUCTNAME Directory
          command: |
            source .venv/bin/activate
            KEEP_COOKIECUTTER_OUTPUT=true ./generate_template.sh
      - run:
          name: Verify cookiecutter matches PRODUCTNAME
          command: test `git status -s \{\{\ cookiecutter.project_name\ \|\ replace\(\'\ \'\,\ \'\'\)\ \}\}/ | wc -l` -eq 0
      # Cache Gems
      - save_cache:
          key: 6-gems-{{ checksum "./PRODUCTNAME/Gemfile.lock" }}-{{ checksum "Gemfile.lock" }}
          # The path to the gems may change if .ruby-version file is changed or CircleCI image is updated.
          paths:
            - "/Users/distiller/.gem/ruby/2.4.4"
      # Cache Pods
      - save_cache:
          key: 3-pods-{{ checksum "./PRODUCTNAME/app/Podfile.lock" }}
          paths:
            - "/Users/distiller/Library/Caches/CocoaPods"
      # Adds SSH key for deploying result to ios-template-output repo
      - add_ssh_keys:
          fingerprints:
            - "33:4f:93:81:10:0e:18:95:86:a8:92:e6:eb:ee:39:92"
      # This allows us to test that the inner CircleCI template is valid by pushing to another remote repo
      # Note: we must delete the Pods folder because otherwise "git add -A" crashes due to OOM.
      - run:
          name: Deploy template to ios-template-output repo
          command: |
            cd ProjectName/app
            rm -rf Pods
            bundle exec pod install
            git add -A
            export COMMIT_MSG="\"https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/commit/$CIRCLE_SHA1\""
            git commit -m $COMMIT_MSG
            git remote add output git@github.com:Raizlabs/ios-template-output.git
            export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_334f9381100e189586a892e6ebee3992'
            git push -u output master:${CIRCLE_BRANCH} --force

workflows:
  version: 2
  test-all:
    jobs:
      - test-xcode-9-3
